[release]
sign-commit = false
sign-tag = false
push = true
tag = true
tag-name = "v{{version}}"
publish = false
execute = true
consolidate-commits = true

[registry]
token = "${CARGO_REGISTRY_TOKEN}"

[github]
release = true
release-draft = false
upload = [
    "smartlocker_linux.tar.gz",
    "smartlocker_windows.zip",
    "target/debian/*.deb",
    "target/generate-rpm/*.rpm"
]
changelog = true
changelog-path = "CHANGELOG.md"
pre-release-hook = ["git", "cliff", "-o", "CHANGELOG.md", "--tag", "{{version}}" ]

# Post-release hook to update and push the changelog
post-release-hook = [
    "git", "add", "CHANGELOG.md",
    "&&", "git", "commit", "-m", "chore: update changelog for version {{version}}",
    "&&", "git", "push"
]