[release]
sign-commit = false
sign-tag = false
push = true
tag = true
tag-name = "v{{version}}"
publish = false
execute = true
consolidate-commits = true

[registry]
token = "${CARGO_REGISTRY_TOKEN}"

[github]
release = false
